# Server config
server:
  port: 8083

# Spring Config
spring:
  data:
    mongodb:
      database: ProjectOne
      host: localhost
  application:
    name: active-operations-service

eureka:
  instance:
    hostname: 20.120.122.181
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    prefer-ip-address: true

# Constants
constants:
  circuit-breaker:
    customer-info-service:
      name: customersServiceCircuitBreaker
      timeout: 2
  status:
    blocked: Blocked
    active: Active
  billing-order:
    paid-status: Paid
    unpaid-status: Unpaid
  customer:
    personal-group: Personal
    business-group: Business
  operation:
    payment-type: Payment
    consumption-type: Consumption
  eureka:
    service-url:
      gateway-service: gateway-service
      customer-info-service: customer-info-service
