# Server config
server:
  port: 8083

# Spring Config
spring:
  data:
    mongodb:
      uri: mongodb://project-1:wF1AmP4bNZM2xh08wd4mxRgcbEnoeUQetRjoCqCKRdUJTuIiHS6TOgu2b4mCFmEHcWZnhdZxEDjI8wKH2CAQyw==@project-1.mongo.cosmos.azure.com:10255/project-1?ssl=true&retrywrites=false&replicaSet=globaldb&maxIdleTimeMS=120000&appName=@project-1@
  application:
    name: active-operations-service

# Eureka config
eureka:
  instance:
    preferIpAddress: true
    serviceUrl:
      defaultZone: http://20.62.234.40:8761/eureka/
  client:
    serviceUrl:
      defaultZone: http://20.62.234.40:8761/eureka/

# Constants
constants:
  circuit-breaker:
    customer-info-service:
      name: customersServiceCircuitBreaker
      timeout: 2
  status:
    blocked: Blocked
    active: Active
  billing-order:
    paid-status: Paid
    unpaid-status: Unpaid
  customer:
    personal-group: Personal
    business-group: Business
  operation:
    payment-type: Payment
    consumption-type: Consumption
  eureka:
    service-url:
      gateway-service: gateway-service
      customer-info-service: customer-info-service
