# Server config
server:
  port: 8083

# Spring Config
spring:
  data:
    mongodb:
      uri: mongodb://${{ secrets.MONGO_RESOURCE_NAME }}:${{ secrets.MONGO_KEY }}@${{ secrets.MONGO_RESOURCE_NAME }}.mongo.cosmos.azure.com:${{ secrets.MONGO_PORT }}/${{ secrets.MONGO_DATABASE_NAME }}?ssl=true&retrywrites=false&replicaSet=globaldb&maxIdleTimeMS=120000&appName=@${{ secrets.MONGO_RESOURCE_NAME }}@
  application:
    name: active-operations-service

# Eureka config
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://20.62.234.40:8761/eureka/

# Constants
constants:
  circuit-breaker:
    customer-info-service:
      name: customersServiceCircuitBreaker
      timeout: 2
  status:
    blocked: Blocked
    active: Active
  billing-order:
    paid-status: Paid
    unpaid-status: Unpaid
  customer:
    personal-group: Personal
    business-group: Business
  operation:
    payment-type: Payment
    consumption-type: Consumption
  eureka:
    service-url:
      gateway-service: gateway-service
      customer-info-service: customer-info-service
