# Server config
server:
  port: 8083

# Spring Config
spring:
  data:
    mongodb:
      database: ProjectOne
      host: localhost
  application:
    name: active-operations-service

eureka:
  instance:
    hostname: localhost
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    prefer-ip-address: true

# Constants
constants:
  status:
    blocked: Blocked
    active: Active
  billing_order:
    paid_status: Paid
    unpaid_status: Unpaid
  customer:
    personal_type: Personal
    business_type: Business
  operation:
    payment_type: Payment
    consumption_type: Consumption
  eureka:
    service_url:
      gateway_service: gateway-service
      customer_info_service: customer-info-service
