# Server config
server:
  port: 8081

# Spring Config
spring:
  data:
    mongodb:
      uri: mongodb://${{ secrets.MONGO_RESOURCE_NAME }}:${{ secrets.MONGO_KEY }}@${{ secrets.MONGO_RESOURCE_NAME }}.mongo.cosmos.azure.com:${{ secrets.MONGO_PORT }}/${{ secrets.MONGO_DATABASE_NAME }}?ssl=true&retrywrites=false&replicaSet=globaldb&maxIdleTimeMS=120000&appName=@${{ secrets.MONGO_RESOURCE_NAME }}@
  application:
    name: customer-info-service

# Eureka config
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://20.62.234.40:8761/eureka/

# Constants
constants:
  status:
    blocked: Blocked
    active: Active
  customer:
    personal_group: Personal
    business_group: Business
