# Server config
server:
  port: 8081

# Spring Config
spring:
  data:
    mongodb:
      uri: mongodb://project-1:wF1AmP4bNZM2xh08wd4mxRgcbEnoeUQetRjoCqCKRdUJTuIiHS6TOgu2b4mCFmEHcWZnhdZxEDjI8wKH2CAQyw==@project-1.mongo.cosmos.azure.com:10255/project-1?ssl=true&retrywrites=false&replicaSet=globaldb&maxIdleTimeMS=120000&appName=@project-1@
  application:
    name: customer-info-service

# Eureka config
eureka:
  instance:
    hostname: localhost
    #preferIpAddress: true
  client:
    serviceUrl:
      #defaultZone: http://20.62.234.40:8761/eureka/
      defaultZone: http://localhost:8761/eureka/

# Constants
constants:
  status:
    blocked: Blocked
    active: Active
  customer:
    personal_group: Personal
    business_group: Business
  kafka:
    credits-topic: credits-topic