# Server config
server:
  port: 8081

# Spring Config
spring:
  data:
    mongodb:
      database: ProjectOne
      host: localhost
  application:
    name: customer-info-service

eureka:
  instance:
    hostname: 20.120.122.181/
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

# Constants
constants:
  status:
    blocked: Blocked
    active: Active
  customer:
    personal_group: Personal
    business_group: Business
