# Server config
server:
  port: 8999

# Eureka config
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://20.62.234.40:8761/eureka/

# Spring Config
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: customer-info-service
          uri: lb://${spring.cloud.gateway.routes[0].id}
          predicates:
            - Path=/${spring.cloud.gateway.routes[0].id}/**
          filters:
            - RewritePath=/${spring.cloud.gateway.routes[0].id}/?(?<remaining>.*), /${remaining}
        - id: passive-operations-service
          uri: lb://${spring.cloud.gateway.routes[1].id}
          predicates:
            - Path=/${spring.cloud.gateway.routes[1].id}/**
          filters:
            - RewritePath=/${spring.cloud.gateway.routes[1].id}/?(?<remaining>.*), /${remaining}
        - id: active-operations-service
          uri: lb://${spring.cloud.gateway.routes[2].id}
          predicates:
            - Path=/${spring.cloud.gateway.routes[2].id}/**
          filters:
            - RewritePath=/${spring.cloud.gateway.routes[2].id}/?(?<remaining>.*), /${remaining}
