# Server config
server:
  port: 8082

# Spring Config
spring:
  data:
    mongodb:
      database: ProjectOne
      host: localhost
  application:
    name: passive-operations-service

eureka:
  instance:
    hostname: localhost
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    prefer-ip-address: true

# Constants
constants:
  status:
    blocked: Blocked
    active: Active
  account:
    current_group: 
      name: Current
      subgroup:
        standard_subgroup: Standard
        pyme_subgroup: PYME
    savings_type: 
      name: Savings
      subgroup:
        standard_subgroup: Standard
        vip_subgroup: VIP
    long_term_type:  
      name: Long term
      subgroup:
        standard_subgroup: Standard
  customer:
    personal_group: 
      name: Personal
      subgroup:
        standard_subgroup: Standard
        vip_subgroup: VIP
    business_group: 
      name: Business
      subgroup:
        standard_subgroup: Standard
        pyme_subgrouup: PYME
  operation:
    deposit_type: Deposit
    withdrawal_type: Withdrawal
  eureka:
    service_url:
      gateway_service: gateway-service
      customer_info_service: customer-info-service
