# Server config
server:
  port: 8082

# Spring Config
spring:
  data:
    mongodb:
      database: ProjectOne
      host: localhost
  application:
    name: passive-operations-service

eureka:
  instance:
    hostname: localhost
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    prefer-ip-address: true

# Constants
constants:
  status:
    blocked: Blocked
    active: Active
  account:
    current_group: 
      name: Current
      subgroup:
        standard: Standard
        pyme: PYME
    savings_group: 
      name: Savings
      subgroup:
        standard: Standard
        vip: VIP
    long_term_group:  
      name: Long term
      subgroup:
        standard: Standard
  customer:
    personal_group: 
      name: Personal
      subgroup:
        standard: Standard
        vip: VIP
    business_group: 
      name: Business
      subgroup:
        standard: Standard
        pyme: PYME
  operation:
    deposit_type: Deposit
    withdrawal_type: Withdrawal
    transfer_in_type: Transfer In
    transfer_out_type: Transfer Out
  eureka:
    service_url:
      gateway_service: gateway-service
      customer_info_service: customer-info-service
      active_operations_service: active-operations-service
